#ifndef SCOPEWINDOW_INC
#define SCOPEWINDOW_INC

class ScopePackage;
class ScopeUnit;
class ScopeEngine;
class ScopePanel;
class ScopeWaveform;
class ScopeVectorscope;
class ScopeHistogram;
class ScopeScopesOn;
class ScopeMenu;
class ScopeGratPaths;
class ScopeGratItem;
class ScopeVectGrats;
class ScopeGainReset;
class ScopeGainSlider;
class ScopeGain;
class ScopeWaveSlider;
class ScopeVectSlider;
class ScopeSmooth;
class ScopeGUI;

#endif
